// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RestaurantMVCDBFirst.Models;

[Table("Menu")]
[Index("CategoryId", Name = "IX_Menu_CategoryId")]
public partial class Menu
{
    [Key]
    public int MenuId { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDT { get; set; }

    public int CategoryId { get; set; }

    public DateTime? UpdatedDT { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Menus")]
    public virtual Category Category { get; set; }
}